run_id: 
dataset:
    - brca_full/cell_type/dataset_shared.yaml

embedding:
    method: scVI
    module: features.scvi_extractor
    class: scVIEmbeddingExtractor
    viz: True
    eval: True
    params:
        batch_key: donor_id
        n_layers: 2
        n_latent: 30
        gene_likelihood: "nb"
        max_epochs: 10
        layer_name: counts #None 
        batch_size: 128
        # njobs: 23

