classification:
    module: models.gf_finetune
    class: GFFineTuneModel
    params:
        model: Geneformer-V2-104M
        version: V2
        model_dir: Geneformer   # MODELS_PATH root (see setup_path.MODELS_PATH)
        dict_dir: Geneformer/gf_dicts_v2 #genefromer 2
        model_input_size: 4096
        batch_size: 32
        epoch: 3
        freeze_layers: 6
        learning_rate: 5e-05
        weight_decay: 0.00001
        warmup_ratio: 0
        train_funcs: 
            - avg
            # - mil
            # - vote
        cv: True
    viz: True
    eval: True

