run_id: 
dataset:
    - brca_full/pre_post/dataset_h5ad_tcells_only.yaml

classification:
    - brca_full/pre_post/classification_randomforest_pre_post.yaml

embedding:
    method: geneformer
    module: features.gf_extractor
    class: GeneformerExtractor
    viz: True
    eval: True
    params: 
        #1- Genefromer 1
        model: Geneformer-V1-10M 
        version: V1
        model_dir: /home/haitham/mnt/MODELS/
        dict_dir: /home/haitham/mnt/gf_dicts_v1 #genefromer 1
        input_size: 4096
        batch_size: 8
        
        # 2-Geneformer 1 (LARGE)
#         model: gf-12L-30M-i2048 
#         model_dir: /home/jupyter/Geneformer2/Geneformer
#         dict_dir: /home/jupyter/Geneformer2/dicts1 #genefromer 1
#         input_size: 2048
        
        # 3-Geneformer 2
        # model: gf-12L-95M-i4096 
        # model_dir: /home/jupyter/Geneformer2/Geneformer
        # dict_dir: /home/jupyter/Geneformer2/dicts2 #genefromer 1
        # input_size: 4096

#         # 4-Geneformer 2 (cancer)
        # model: gf-12L-95M-i4096_CLcancer
        # model_dir: /home/jupyter/Geneformer2/Geneformer
        # dict_dir: /home/jupyter/Geneformer2/dicts2 #genefromer 1
        # input_size: 4096
        # batch_size: 8

