run_id: 
dataset:
    - brca_full/pre_post/dataset_h5ad_tcells_only.yaml

classification:
    - brca_full/pre_post/classification_randomforest_pre_post.yaml

    
embedding:
    method: scgpt
    module: features.scgpt_extractor
    class: scGPT_Exractor
    viz: False
    eval: False
    params: 
        #Human
        model: scGPT_human
        model_dir: /home/haitham/mnt/MODELS/scGPT
        batch_size: 16
        n_bins: 51
        max_seq_len: 2048

