run_id: 
dataset:
    - brca_full/pre_post/dataset_h5ad_tcells_only.yaml

classification:
    - brca_full/pre_post/classification_randomforest_pre_post.yaml

embedding:
    method: scVI
    module: features.scvi_extractor
    class: scVIEmbeddingExtractor
    viz: True
    eval: True
    params:
        batch_key: cell_types
        n_layers: 2
        n_latent: 100
        gene_likelihood: "nb"
        max_epochs: 10
        layer_name: #None 
        batch_size: 217

