classification:
    module: models.gf_finetune
    class: GFFineTuneModel
    params:
        model: Geneformer-V1-10M
        version: V1
        model_dir: Geneformer   # MODELS_PATH root (see setup_path.MODELS_PATH)
        dict_dir: Geneformer/gf_dicts_v1 #genefromer 2
        model_input_size: 2048
        batch_size: 64
        epoch: 5
        freeze_layers: 2
        learning_rate: 0.00001
        train_funcs: 
            - avg
            # - mil
            # - vote
        cv: True
        # onesplit: True
    viz: True
    eval: True