run_id: 
dataset:
    - brca_full/outcome/dataset_shared.yaml

embedding:
    method: scgpt
    module: features.scgpt_extractor
    class: scGPT_Exractor
    viz: True
    eval: True
    params: 
        #Human
        model: scGPT_cancer
        model_dir: /home/jupyter/MODELS_old/scGPT
        batch_size: 16
        n_bins: 51
        max_seq_len: 2048

