run_id: 
dataset:
    - luad1/dataset_shared.yaml

embedding:
    method: scgpt
    module: features.scgpt_extractor
    class: scGPT_Exractor
    viz: False
    eval: False
    params: 
        #Human
        model: scGPT_cancer
        model_dir: /home/jupyter/MODELS_old/scGPT
        batch_size: 16
        n_bins: 51
        max_seq_len: 1200

