run_id: 
dataset:
    - luad1/dataset_shared.yaml

embedding:
    method: geneformer
    module: features.gf_extractor
    class: GeneformerExtractor
    viz: True
    eval: True
    params: 
        #1- Genefromer 1
        # model: Geneformer-V1-10M 
        # version: V1
        # model_dir: /home/jupyter/MODELS/Geneformer/
        # dict_dir: /home/jupyter/MODELS/Geneformer/geneformer/gene_dictionaries_30m #genefromer 1
        # input_size: 2048
        # batch_size: 8
        
        # 2-Geneformer 1 (LARGE)
#         model: gf-12L-30M-i2048 
#         model_dir: /home/jupyter/Geneformer2/Geneformer
#         dict_dir: /home/jupyter/Geneformer2/dicts1 #genefromer 1
#         input_size: 2048
        
        # 3-Geneformer 2
        # model: Geneformer-V2-104M
        # version: V2
        # model_dir: /home/jupyter/MODELS/Geneformer
        # dict_dir: /home/jupyter/MODELS/Geneformer/geneformer #genefromer 2
        # input_size: 4096

#         # 5-Geneformer 2 326M
        model: Geneformer-V2-316M
        version: V2
        model_dir: /home/jupyter/mnt/MODELS
        dict_dir: /home/jupyter/mnt/gf_dicts_v2 #genefromer 2
        input_size: 4096
        batch_size: 8

    eval: True